### ISSUE TITLE
LastPass: Multi-line field and in-line delimiter problems

### ISSUE THREAD

**Issue by srccd** [buttercup/buttercup-importer#14]
I utilize the Notes field in LastPass to store comments. Sometimes this field will be multiple lines of text and sometimes it will include a comma (the standard delimiter).  LastPass properly exports this field with quotes. However, when I import to Buttercup, the CSV translation fails. Including a sample CSV:

```
url,username,password,extra,name,grouping,fav
http://test0.com,uname0,pwd0,"This one works.",title0,Category0,0
http://test1.com,uname1,pwd1,"This one does not work due to in line delimiter. Port list: 119, 23, 1818 or 8080; Tested in May 2017, using in line delimiter and line breaks",title1,Category1,0
http://test2.com,uname2,pwd2,"This one does not work due to line breaks.
Line 2.
Line 3.
And so on.",title2,Category2,0
```

**Comment by perry-mitchell** [comment]
Thanks @srccd. CSV format does specify that multi-line values may occur within quotes as you've shown. We'll have to get this fixed up.

We should check if the [`csvjson`](https://www.npmjs.com/package/csvjson) library we're using supports multiline values. We could fix it upstream if it doesn't.

**Comment by perry-mitchell** [comment]
**Note** to add a multiline test case when fixing.
