### ISSUE TITLE
Importing from 1Password archive failed: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by mannp** [buttercup/buttercup-importer#24]
v1.2.1 on MacOS

The following was in the Mac log.

> Feb 16 16:06:38 Mac Buttercup[12475]: assertion failed: 17E139j: libxpc.dylib + 72221 [8B04A1F3-E354-3228-932B-832DE71594A1]: 0x89
> Feb 16 16:06:40 Mac Buttercup[12475]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
> Feb 16 16:20:11 Mac Buttercup[12475]: objc[12475]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9f2cfcb0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11b2a0cd8). One of the two will be used. Which one is undefined.

**Comment by perry-mitchell** [comment]
Hi @mannp - Any chance you could see if there's anything in the bcup logs? They're [here](https://github.com/buttercup/buttercup-desktop/blob/49a057d5272dadaf4bab2905cb516d307c88c672/README.md#debugging).

**Comment by mannp** [comment]
Hi @perry-mitchell sadly nothing at all in the log, which is odd?

Retried the import with the same error but again nothing in the log.
