### ISSUE TITLE
1password export support (1pif)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-importer#4]
Support exporting 1password databases that have been exported to 1pif.

**Comment by zeke** [comment]
🙏

**Comment by perry-mitchell** [comment]
I guess this is next on our list. Let's have a call later @sallar? You're more familiar with the 1password structure. There's a lot of rich information in 1password archives that we don't yet support that will be lost unfortunately with an initial release, but we can work on it later.

**Comment by sallar** [comment]
@perry-mitchell I have been trying to avoid this :D yes they have lots of fields, but yes lets have a call and discuss it :+1:

**Comment by perry-mitchell** [comment]
Some items to help with this:

 * https://www.npmjs.com/package/1pif-to-csv
 * https://github.com/phoenixlzx/1password2pass/blob/master/lib/parse.js

**Comment by perry-mitchell** [comment]
Done.. in review :)
