### ISSUE TITLE
Not working in windows / linux [req tutorial]

### ISSUE THREAD

**Issue by rugabunda** [buttercup/buttercup-importer#41]
I installed nodejs, pify via npm as requested, when trying to run any *.js file it says nothing, via `node KeePass2XMLImporter.js` I see an empty prompt... I tried for example `KeePass2XMLImporter.js passwordfilename` with no result.  How does one run this, can you please add a tutorial.  Thanks.

same result in windows as linux no matter which js is run

**Comment by perry-mitchell** [comment]
Apologies, this could be documented better. This library is just that: a library. It doesn’t have any CLI functionality. To import vaults use the buttercup desktop application. I’ll update the docs now.

**Comment by rugabunda** [comment]
thanks perry wild that explains it all... well, is it possible to transport an import from the desktop application into the browser extension?

**Comment by perry-mitchell** [comment]
Absolutely - import to a vault that’s stored within a cloud storage platform like Dropbox or WebDAV. Once imported you should see the changes in the browser extension (after it reloads the contents of course).

**Comment by rugabunda** [comment]
> 
> 
> Absolutely - import to a vault that’s stored within a cloud storage platform like Dropbox or WebDAV. Once imported you should see the changes in the browser extension (after it reloads the contents of course).

tx perry! much appreciated; trying to get your app on this great program here https://patchmypc.com/forum/index.php?topic=3434.msg8968#msg8968

**Comment by perry-mitchell** [comment]
@rugabunda Hey that's neat! Thanks a lot for the shout out and kind works. It'd be excellent to see it added to toolkits like that.

Please let us know if you hear back :)
