### ISSUE TITLE
Support for Key Files (KeePass 2)

### ISSUE THREAD

**Issue by GecoMynx** [buttercup/buttercup-importer#5]
It's not possible to import a KeePass 2 DB when it's encrypted with a Passphrase and a Key File.

**Comment by perry-mitchell** [comment]
This will require keyfile support in the GUI - buttercup/buttercup#69

**Comment by jeroen7s** [comment]
it's also not possible to import ones that use argon
i just opened mine in keepassxc, "saved as" a new database, and then changed Argon back to AES-KDF and then removed the key file to import it

**Comment by riyadhalnur** [comment]
If this is still available, I'd like to pick this up.

**Comment by perry-mitchell** [comment]
@riyadhalnur It is! I'll assign it to you :)

**Comment by riyadhalnur** [comment]
Opened the PR for support for key files. Will work on integrating with the application once it's merged.
